### ISSUE TITLE
Outdated link to the `async-std` driver

### ISSUE THREAD

**Issue by DarkEld3r** [cfsamson/books-futures-explained#13]
The link (https://github.com/async-rs/async-std/blob/master/src/net/driver/mod.rs) to the `async-std` driver in the "Avoid wrapping the whole Reactor in a mutex and pass it around" section is broken. I wasn't able to find it quickly, otherwise I would have submitted a pull request.

**Comment by cfsamson** [comment]
Thanks. Yes, it seems there has been quite a bit of changes since I last looked at it. I hope I've found some new links to serve as entry points for further explorations to both async_std and tokio. Permalinks this time though :)
