### ISSUE TITLE
Most recent waker not registered on multiple calls to poll

### ISSUE THREAD

**Issue by cfsamson** [cfsamson/books-futures-explained#2]
As noted in this reddit comment: https://www.reddit.com/r/rust/comments/fwiet3/futures_explained_in_200_lines_of_rust/fmrwxh8?utm_source=share&utm_medium=web2x

On multiple calls to `Poll` only the `Waker` passed from the most recent call should be scheduled to recieve a wakeup. In the current implementation we only return `Pending`, but we should re-register the context and remove the old one. This shows how this can cause a problem:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=940ede047b9019e41f5aabdadb0dbb66

I'll dig into this in a couple of days when I have some time to improve the current example and go through all the details.

**Comment by cfsamson** [comment]
Ok, so this is a possible fix, but I'll take a pass on the example code to see if I can clean it up a bit. For example, the argument `data` is later use as `id` which makes it difficult to follow. Maybe readylist can be removed now that we have a collection of Wakers that can carry some extra information...

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4bb8133eba62f8a5e16951e5e1f9081a

**Comment by cfsamson** [comment]
This ended up as a rather big rewrite of the Reactor and `Poll` to solve the problem mentioned here, but also a possible race condition in our `Poll` method:

```rust
r.register(self.data, cx.waker().clone(), self.id);
            drop(r); // <---- NB!
            self.is_registered = true;
            Poll::Pending
```
If the `Future` completes immidiately, it could call `Wake` while we're still in our poll method resulting in a `wake` that never gets caught. In addition I added several Readability improvements which I believe resulted in a much better `Reactor` example.

**Comment by nkbai** [comment]
there is still race condition between the return of poll and thread.park.  this will cause call thread.park after wake. 
```
// ============================= EXECUTOR ====================================
fn block_on<F: Future>(mut future: F) -> F::Output {
    let mywaker = Arc::new(MyWaker {
        thread: thread::current(),
    });
    let waker = waker_into_waker(Arc::into_raw(mywaker));
    let mut cx = Context::from_waker(&waker);

    // SAFETY: we shadow `future` so it can't be accessed again.
    let mut future = unsafe { Pin::new_unchecked(&mut future) };
    let val = loop {
        match Future::poll(future.as_mut(), &mut cx) {
            Poll::Ready(val) => break val,
            Poll::Pending => {
                thread::sleep(std::time::Duration::from_millis(100));
                println!("executor parked");
                thread::park()
            }
        };
    };
    val
}
```

**Comment by nkbai** [comment]
https://github.com/stjepang/byo-executor/blob/master/examples/v1.rs  it's the executor's responsibility to make sure that park/unpark is  ordered.

**Comment by cfsamson** [comment]
@nkbai Yes, but I do mention the possible race conditions in the executor (though, I could word it differently). 

AFAIK it's not easily fixed without changing park mechanism to something like [crossbeam::parker](https://docs.rs/crossbeam-utils/0.7.0/src/crossbeam_utils/sync/parker.rs.html#54-57) or roll your own using a [condvar](https://doc.rust-lang.org/stable/std/sync/struct.Condvar.html) like shown below, but we end up having to explain a lot about synchonization so I left that as an excersise for the reader.

I'm still a bit usure if it was smart to leave the example in an "incorrect" state like this though. I could add the simple park/unpark mechanism below and explain it even though it adds at least one more paragraph to the book (I think this is free from all kinds of races if I make this change though):

What do you think about extending the book a little bit more but make it correct?

```rust
#[derive(Default)]
struct Parker(Mutex<bool>, Condvar);

impl Parker {
    fn park(&self) {
        let mut resumable = self.0.lock().unwrap();
            while !*resumable {
                resumable = self.1.wait(resumable).unwrap();
            }
        *resumable = false;
    }

    fn unpark(&self) {
        *self.0.lock().unwrap() = true;
        self.1.notify_one();
    }
}

fn block_on<F: Future>(mut future: F) -> F::Output {
    let parker = Arc::new(Parker::default());
    let mywaker = Arc::new(MyWaker { parker: parker.clone() });
    let waker = waker_into_waker(Arc::into_raw(mywaker));
    let mut cx = Context::from_waker(&waker);

    // SAFETY: we shadow `future` so it can't be accessed again.
    let mut future = unsafe { Pin::new_unchecked(&mut future) };
    let val = loop {
        match Future::poll(future.as_mut(), &mut cx) {
            Poll::Ready(val) => break val,
            Poll::Pending => parker.park(),
        };
    };
    val
}
```

And change our Waker implementation in these two places:
```rust
#[derive(Clone)]
struct MyWaker {
    parker: Arc<Parker>,
}


fn mywaker_wake(s: &MyWaker) {
    let waker_ptr: *const MyWaker = s;
    let waker_arc = unsafe { Arc::from_raw(waker_ptr) };
    waker_arc.parker.unpark();
}
```

**Comment by cfsamson** [comment]
@nkbai I found a way to create a concise explanation for this, so I decided to add a "Bonus Section" to the [Implementing Futures chapter](https://cfsamson.github.io/books-futures-explained/6_future_example.html) and change the [Finished Example](https://cfsamson.github.io/books-futures-explained/8_finished_example.html) accordingly so it reflects these changes.

There is also some changes to the "Reader Exercises" chapter since one of the exercises is now part of the main example. See commit https://github.com/cfsamson/books-futures-explained/commit/d9eb756ef7e708e150f81721728335a222a7e019 for more information.

**Comment by nkbai** [comment]
What problem are you trying to solve with CondVar? The original Thread :: Park / Unpark can work normally, and there is no problem that the thread cannot be woken.

I have tested, even if you call UnPark first, and then Park, Park will return immediately.

**Comment by nkbai** [comment]
by the way, what does `NB!` mean?

**Comment by cfsamson** [comment]
`NB!` means [Nota Bene](https://en.wikipedia.org/wiki/Nota_bene) in latin, in practice it's the same as "make a note of this".

I can best describe the problem this way but it's hard to reproduce (I can't prove that this will happen in practice but I think the logic is sound):

1. Two futures are registered with the executor using a method which runs them concurrently (like [fututres::future::join_all](https://docs.rs/futures/0.3.4/futures/future/fn.join_all.html)
2. Future 1 resolves and wakes up the executor thread
3. While calling `poll` on the future the reactor is locked so no other future can call `wake` - so far so good.
4. However, after the first future is resolved and returns `Ready` we again poll the second future which returns `Pending`
5. Now, after we return from calling `poll` and get the `Pending` result, we have released the lock on the reactor so it's possible to call `wake` from our reactor-thread. There is a split second before we call `thread::park` where a waker could call `unpark` from our reactor-thread while we're still awake. IF our last future wakes up at that exact point and call `unpark` in this exact "gap" we will still call `thread::park`.
6. Since the waker has been called it will not be called again and we're deadlocked

In practice I think it's highly unlikely to happen, and since acquiring a mutex lock and make the call to wake is relatively slow compared to just returning from a function and then calling `park` I'm pretty sure that it won't happen in our example. 

However, in theory, nothing prevents this from happening since there are two threads competing on calling unpark/park.

A more realistic problem is that that our async/await blocks could be spawning threads themselves calling park/unpark on the handle to our executor thread which can cause unwanted behavior.

By creating our own Parker using a Condvar we avoid all these potential issues. There might also be more that I'm not aware of.

The added complexity, and the unlikeliness of this beeing a problem in this example was the reason I first skipped it.

**Comment by nkbai** [comment]
```rust
 let val = loop {
        match Future::poll(future.as_mut(), &mut cx) {
            Poll::Ready(val) => break val,
            Poll::Pending => {
                thread::sleep(std::time::Duration::from_millis(100));
                println!("executor parked");
                thread::park()
            }
        };
    };
```

I don't know if I did what you described? Sleep before the park and make sure that reactor finish unpark. But this will not deadlock, because the park is called immediately after unpark, the park will return immediately.

The result is the same for CondVar. After notify_one, wait is called immediately and it returns immediately.

**Comment by nkbai** [comment]
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=92947229eab1a822825c4b946edab056

CondVar can indeed avoid the problem you said, other functions of the thread will call park / unpark.

If other functions in the thread are not allowed to call park / unpark, then Thread :: park / unpark and CondVar are equivalent.

**Comment by cfsamson** [comment]
> I don't know if I did what you described? Sleep before the park and make sure that reactor finish unpark. But this will not deadlock, because the park is called immediately after unpark, the park will return immediately.

Yeah, park/unpark worked a bit differently than I first thought. I tried to get it to deadlock that way myself, but couldn't since park returns immediately as you say.

The real problem is the last one I described. Yes, if no calls to park/unpark is allowed they're the same, but in real life I think the problem is libraries using calls to park/unpark for synchronization (like `once_cell` does when initializing the value) so you'd have to check all libraries for and that or it can create some problems that can be really hard to debug.

I updated the book with a link to the playground with the last example to explain why using park/unpark is a bad idea, so I think I've covered this pretty good now.

**Comment by nkbai** [comment]
Great! I translated your article into Chinese and haven't had time to update to the latest version, but I will update to the latest version soon.

https://stevenbai.top/rust/futures_explained_in_200_lines_of_rust/

**Comment by cfsamson** [comment]
That's cool! 

I can add a link to the translation in the introduction-page so those who prefer have the option to read it in their native language. Give me a heads up when you've made the latest updates and I'll add the link.

**Comment by nkbai** [comment]
this link will not change after I update  to the latest version.  it's the version of several  days ago  right now.

**Comment by cfsamson** [comment]
OK, I'll add it as soon as I have a little time to push an update.
