### ISSUE TITLE
Waker: same implementation for wake and wake_by_ref

### ISSUE THREAD

**Issue by mikewatt** [cfsamson/books-futures-explained#22]
Thanks for this book, I've learned a lot reading through it!

In the section where a Waker is implemented (https://cfsamson.github.io/books-futures-explained/6_future_example.html#the-future-implementation), the same function is used for both `wake` and `wake_by_ref`:

```
fn mywaker_wake(s: &MyWaker) {
    let waker_ptr: *const MyWaker = s;
    let waker_arc = unsafe {Arc::from_raw(waker_ptr)};
    waker_arc.thread.unpark();
}

...

const VTABLE: RawWakerVTable = unsafe {
    RawWakerVTable::new(
        |s| mywaker_clone(&*(s as *const MyWaker)),     // clone
        |s| mywaker_wake(&*(s as *const MyWaker)),      // wake
        |s| mywaker_wake(*(s as *const &MyWaker)),      // wake by ref
        |s| drop(Arc::from_raw(s as *const MyWaker)),   // decrease refcount
    )
};
```

I don't see `wake_by_ref` used anywhere in the code, but I was confused as to whether or not this would be correct in practice. Should there be a separate implementation of `wake_by_ref` that does not allow the `Arc` to drop (decreasing the ref count)?

**Comment by cfsamson** [comment]
Thanks. Thats really nice to hear.

I think you're right. Good catch! It's been some time since I wrote this and I can't remember my reasoning there exactly but looking over it with fresh eyes something like this looks better since it won't decrease the refcount:

```rust
const VTABLE: RawWakerVTable = unsafe {
    RawWakerVTable::new(
        |s| mywaker_clone(&*(s as *const MyWaker)),   // clone
        |s| mywaker_wake(&*(s as *const MyWaker)),    // wake
        |s| (*(s as *const MyWaker)).parker.unpark(),    // wake by ref
        |s| drop(Arc::from_raw(s as *const MyWaker)), // decrease refcount
    )
};
```
