### ISSUE TITLE
Suggestion: Emphasize Reactors more

### ISSUE THREAD

**Issue by ckaran** [cfsamson/books-futures-explained#25]
One of the issues I had starting out with futures (both in the standard library and in [`futures`](https://crates.io/crates/futures)) was figuring out where the wakers got called.  For some reason, I got it fixed into my head that there are only two 'real' parts to the system, the thing that implements [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html), and the executor.  I couldn't see how the wakers were involved *at all*.  Reading through your code, I can see that the wakers are shared objects between the future, the executor, and the reactor, with the *executor* being the one to create the waker.  So, my suggestion is that you make the following heavily emphasized (and cleaned up, you're a good technical writer and teacher!):

"""
- The futures system consists of 3 parts, the executor, the future, and the reactor.
    - The future is what you want executed.
    - The executor is what actually runs the future.
    - The reactor is what tells the executor that one or more futures are ready to continue processing.

The primary connection between these three parts is an object called a **Waker.**  The Waker is a shared object that the reactor uses to tell the executor that the future is ready to run.  Once you understand the lifecycle and ownership of a Waker, you'll understand how futures work from a user's perspective.  Here is the lifecycle:

- A Waker is created by the **executor.**
- When a future is registered with an executor, it is given a clone of the Waker that was created above.  Since this is a shared object (e.g., an `Arc<T>`), all clones actually point to the same underlying object.
- The future clones the Waker and passes it to the reactor, which stores it to use later.

At some point in the future, the reactor will decide that the future is ready to run.  It will wake the future via the Waker that it stored.  This action will do what is necessary to get the executor in a position to poll the future.  The Waker object implements everything that we associate with [`task`](https://doc.rust-lang.org/std/task/index.html).  The object is specific to the type of executor in use, but all such objects share a similar interface (not actually a trait because embedded systems can't handle trait objects, but a useful abstraction is to think of it as a trait object).  Because the interface is the same across all executors, reactors can be completely oblivious to the type of the executor, and vice-versa.  **Executors and reactors never need to communicate with one another directly.**

This design is what gives the futures framework it's power and flexibility.  Because they aren't directly coupled, it is possible to change executors or reactors at any time.  It is also possible to have more than one executor or reactor running at the same time.  E.g., you might have an executor for the UI elements and an executor for computation.  The UI executor might have one thread, while the compute executor has more.  You could have UI futures that await computation futures to update the UI, and UI futures that are triggered by one or more reactors (e.g., the touch screen reactor, the keyboard reactor, etc.).  Each of these parts can live largely in isolation from the other parts, allowing you to add or remove reactors as needed (e.g., when a new USB device is added or removed).  
"""

Anyways, that's roughly the line I was thinking of.  That might expand you past 200 lines, but it would have helped me out earlier if I'd had that to read, and I'm guessing others may be in the same boat as me, which is why I wanted to pass the idea along to you.

**Edit**

Fixed a broken link above.  

Also, I just realized that my suggestion above incorrectly implies that there is only one Waker object, not one per future.  Yet another part of the cleanup that needs to be done!

**Comment by cfsamson** [comment]
Hi. Thanks for the concrete suggestion and the nice feedback. Your intuition about the subject mirrors my own. In an earlier draft I actually did emphasize this more, but after some discussion with @jonhoo I actually toned it down a bit. 

He asked if it's really true that the reactor and executor could be as loosely coupled as suggested by the model you (and I did) describe, and argued that they need to cooperate pretty closely. He also argued that neither executors or reactors is a "thing" as far as Rust's futures model is concerned and that they're just an aspect of a particular runtime, but both async_std and tokio has moved away from using these names (which they did just before I finished this book).

My counterarguments was that if there were no implicit concept of a loose coupling between an "Executor" and a "Reactor" there is no reason to implement the Waker just the way they did. A simple token (which could be an integer or a pointer) to identify the task represented by the waker would suffice and simplify the implementation if there is an implicit tight coupling where futures are created and driven by the same runtime.

There is also this quote from the blog series about the futures design by Withoutboats: https://boats.gitlab.io/blog/post/wakers-i/

>...The executor and the reactor form the two halves of what in most asynchronous computing systems is called the “event loop.” One of the great things about Rust’s design is that you can combine different executors with different reactors, instead of being tied down to one runtime library for both pieces.

Since the runtimes which existed in Rust at the moment of writing took a step away from the reactor/executor terminology, and there were more and more talk about a ["generic rutime interface"](http://smallcultfollowing.com/babysteps/blog/2020/07/09/async-interview-8-stjepan-glavina/), I was reluctant to push the reactor/executor model too far and landed on the wording as seen in the book now. I didn't want to promote an idea that was disputed and go too much into the weeds of a specific runtime implementation.

Now, with that said, I agree with you that it makes it more difficult to get a good intuition about the subject. I do think that the major reason that we have more tightly coupled runtimes in Rust today is that you need locks like `Mutexes`, delays like `Sleep`  and async implementations of things in the `std::file` module for a runtime to be `easy and ergonomic` to use. This is especially true in the web-sphere where something simple as establishing a TCP connection could involve a DNS lookup in a threadpool, and the rest of the negotiation is done using something like `epoll`. 

I still think there is merit to the idea about a loose coupling between the executor-part and the reactor-part of the runtime and I think it's a good model for learning. There is also the fact that the code in my example leans on this model so I'm leaning towards changing it according to your suggestion. 

I'll try to mix in your paragraph and how it looks when I have a little spare time.

Sorry for the lengthy answer but since I've "been down that road before" I thought I'd add a bit of context while thinking out loud.

**Comment by ckaran** [comment]
> Sorry for the lengthy answer but since I've "been down that road before" I thought I'd add a bit of context while thinking out loud.

Actually, I appreciate the lengthy answer!  It gives me context to decisions that you had to make.

> I still think there is merit to the idea about a loose coupling between the executor-part and the reactor-part of the runtime and I think it's a good model for learning. There is also the fact that the code in my example leans on this model so I'm leaning towards changing it according to your suggestion.

It's the learning part that I'm most interested in.  The explanation that withoutboats gives makes it quite clear as to what kind of model he was thinking about, but the documentation in the standard library doesn't make this clear enough (yet).  That's why I appreciate that you're willing to 'tone it up' again.  I can see where Jon Gjengset is coming from, but the issue is that when you're learning something new, you really need as much help as possible, and a simplified explanation helps a lot.  The loosely-coupled reactor model is a good teaching tool, but if you want to give other models as well, that could be helpful.

Thank you again for writing this book, and for being willing to modify it further!

**Comment by cfsamson** [comment]
No problem. It's good with suggestions like this one which also gives me a fresh view on it. 

I'll sit down and take a closer look at it when I get to free up some time, hopefully pretty soon. I'll report back this here once I've got something ready.

**Comment by cfsamson** [comment]
@ckaran If you have time. I'm reworking the chapter as we talked about but I thought it might be nice to include a GIF which tries to explain the flow. Grated, I'm not an expert in animations but I gave it a try and wondered if it's confusing or if its helpful to include somthing like this:

![futures_animation](https://user-images.githubusercontent.com/8337848/102775151-9ccb8c80-438c-11eb-91b9-1d17bdaff5b4.gif)

**Comment by cfsamson** [comment]
Ok, so I ended up changing the "Runtimes" paragraph and added it there. I really liked what you wrote but I shortened it somewhat and added the animation (which might or might not work out, but I'll let it stay for now). Thanks for the help!

https://cfsamson.github.io/books-futures-explained/1_futures_in_rust.html#runtimes

**Comment by ckaran** [comment]
I like the updates, but would like to make two suggestions:

- Split each of the frames of the GIF into separate images, if not on that page then on another page.  The animation is just fast enough that I can't keep up with it, and I had to eventually split the frames up so I could look at each one individually.  Having all of them on one page, in order, would make it easier to compare two frames to see what changed.
- Expand on what the waker is doing.  For example, show that the executor has a ready queue and a pending queue, and have the waker move the future from one to the other, and then prod the executor to get it to wake up (or if you're using something like a crossbeam deque, make it clear that the executor is a consuming out of the ready queue, and will therefore wake up as soon as anything is put into the queue).

Other than that, I really like the changes!

**Comment by cfsamson** [comment]
Thanks. 

Yeah. I agree. I've looked at the animation a few times now, and it should be only graphics (no code) so it's possible to follow. I'll take one more stab at it, I have an idea that might work without any text and visualize a bit better what the Waker is doing as well. It's not crucial if it doesn't work out.

**Comment by ckaran** [comment]
Actually, I think leaving the code in there makes it clearer.  If you remove the code, it gets so high-level that it gets to be harder to follow.  If anything, I'd say split the frames into individual pages, and add lots of notes about what is going on.  Futures remind me a lot of physics; until you understand the math, it's hopeless and you need all the help you can get.  Once you understand the math, everything is trivial, and you want to clear it all away because it's 'obvious'.  Really get into the meat of it will help someone who's never seen it before much more than a high-level graphic will.

**Comment by cfsamson** [comment]
You're right. After some time it gets difficult to judge what's obvious and not. I'll present them as individual pages and explain a little bit more on each page since readers will have more than 3 secs to read them this way :) Let's see how that looks when I'm done.

**Comment by ckaran** [comment]
> You're right. After some time it gets difficult to judge what's obvious and not.

That's *exactly* like physics! :wink: 

If you're willing to ping me when you get it done, I'm willing to take a look at it and give you my opinion.

**Comment by cfsamson** [comment]
Shure. Thanks! I'll ping back when I'm done 👍

**Comment by cfsamson** [comment]
@ckaran Ok, so I got something that I think might work. I'm just considering how to best present them. I'm thinking this could be a new chapter after the chapter 2 where I just present the slides. It adds some length to the book but they should be fairly easy and fast to read through (I hope):

![futures1](https://user-images.githubusercontent.com/8337848/102892202-ce615800-445f-11eb-8f91-1cc6b0b3e678.PNG)
![futures2](https://user-images.githubusercontent.com/8337848/102892207-d02b1b80-445f-11eb-844a-f2ab41ae1168.PNG)
![futures3](https://user-images.githubusercontent.com/8337848/102892210-d1f4df00-445f-11eb-853d-f94fc5e562fe.PNG)
![futures4](https://user-images.githubusercontent.com/8337848/102892215-d3bea280-445f-11eb-8bde-ca9b5358c228.PNG)
![futures5](https://user-images.githubusercontent.com/8337848/102892219-d620fc80-445f-11eb-8bb2-a8bf53f1cc2d.PNG)
![futures6](https://user-images.githubusercontent.com/8337848/102892229-d7eac000-445f-11eb-97f5-beb35471a86f.PNG)
![futures7](https://user-images.githubusercontent.com/8337848/102892231-d91bed00-445f-11eb-8a01-6a9e54544828.PNG)
![futures8](https://user-images.githubusercontent.com/8337848/102892234-dae5b080-445f-11eb-8ea4-88f3427a807a.PNG)
![futures9](https://user-images.githubusercontent.com/8337848/102892239-dc16dd80-445f-11eb-9bf9-49fa28b94ea3.PNG)
![futures10](https://user-images.githubusercontent.com/8337848/102892241-dde0a100-445f-11eb-9a55-f4fbb1d46ba2.PNG)
![futures11](https://user-images.githubusercontent.com/8337848/102892247-dfaa6480-445f-11eb-9638-c6554a340d78.PNG)
![futures12](https://user-images.githubusercontent.com/8337848/102892252-e1742800-445f-11eb-8c50-3e11d19842cf.PNG)
![futures13](https://user-images.githubusercontent.com/8337848/102892256-e3d68200-445f-11eb-8ed5-90e483ab476a.PNG)
![futures14](https://user-images.githubusercontent.com/8337848/102892262-e507af00-445f-11eb-9130-93c142de02c6.PNG)
![futures15](https://user-images.githubusercontent.com/8337848/102892265-e6d17280-445f-11eb-84b1-777c997682da.PNG)
![futures16](https://user-images.githubusercontent.com/8337848/102892268-e8029f80-445f-11eb-90a6-f0e5d295207c.PNG)
![futures17](https://user-images.githubusercontent.com/8337848/102892270-e933cc80-445f-11eb-9332-7343b07f6e71.PNG)

**Comment by ckaran** [comment]
**MUCH NICER!!!** That makes things much, much clearer than before, thank you!

The only thing that I can think to add to this would be an explanation of what `async` functions compile into.  That is, what does the compiler turn the following in to?

```rust
let non_leaf_fut = async {
    let leaf_fut = Reactor::new_io(...);
    let result = leaf_fut.await;
};
```

The reason I'm mentioning this is that the async function is not *visibly* passing the waker to the leaf future, and yet somehow it must be being passed in.  Moreover, we know that the poll method is being called repeatedly, so it must somehow know which portions of the code were already executed (`let leaf_fut = Reactor::new_io(...);`) vs. the parts that have just now finished executing.  This will make the state machine much more clear.  That said, you will likely need to explain that you're just showing an example of what is going on, and may not be what the compiler is doing under the hood.

Overall though, I really like the direction you're taking this in, it makes it much clearer for newbies!

**Comment by cfsamson** [comment]
Great, thanks 😅 . Yeah, you're right. That is poorly explained right now. I think doing like this (below) might be better (however, it's starting to get fairly complex):

![Slide1](https://user-images.githubusercontent.com/8337848/102914188-345dd780-4480-11eb-9127-79c7607ee38a.PNG)
![Slide2](https://user-images.githubusercontent.com/8337848/102914189-345dd780-4480-11eb-995f-c6ae3892cb87.PNG)
![Slide3](https://user-images.githubusercontent.com/8337848/102914191-345dd780-4480-11eb-8e3c-85053afbe451.PNG)
![Slide4](https://user-images.githubusercontent.com/8337848/102914193-34f66e00-4480-11eb-9a74-89229dbb3975.PNG)
![Slide5](https://user-images.githubusercontent.com/8337848/102914194-34f66e00-4480-11eb-8393-b6beb98c9be6.PNG)
![Slide6](https://user-images.githubusercontent.com/8337848/102914196-358f0480-4480-11eb-85f4-cefd0c23e73e.PNG)
![Slide7](https://user-images.githubusercontent.com/8337848/102914197-358f0480-4480-11eb-9f9b-e25ff3e70fdd.PNG)
![Slide8](https://user-images.githubusercontent.com/8337848/102914198-358f0480-4480-11eb-9fa2-69e29ad53fb3.PNG)
![Slide9](https://user-images.githubusercontent.com/8337848/102914199-36279b00-4480-11eb-9479-315c13346305.PNG)
![Slide10](https://user-images.githubusercontent.com/8337848/102914173-3162e700-4480-11eb-9192-c063abcadf01.PNG)
![Slide11](https://user-images.githubusercontent.com/8337848/102914176-31fb7d80-4480-11eb-968e-a5f0c992421b.PNG)
![Slide12](https://user-images.githubusercontent.com/8337848/102914179-32941400-4480-11eb-91c9-0476e2dce85e.PNG)
![Slide13](https://user-images.githubusercontent.com/8337848/102914180-32941400-4480-11eb-9cdd-b246bd3193d6.PNG)
![Slide14](https://user-images.githubusercontent.com/8337848/102914182-32941400-4480-11eb-9997-bd183edc4542.PNG)
![Slide15](https://user-images.githubusercontent.com/8337848/102914183-332caa80-4480-11eb-99d1-48c0accfc358.PNG)
![Slide16](https://user-images.githubusercontent.com/8337848/102914184-332caa80-4480-11eb-83da-41b053578a5f.PNG)
![Slide17](https://user-images.githubusercontent.com/8337848/102914185-33c54100-4480-11eb-94c4-de67048144d8.PNG)
![Slide18](https://user-images.githubusercontent.com/8337848/102914186-33c54100-4480-11eb-886d-b08878aa46ae.PNG)
![Slide19](https://user-images.githubusercontent.com/8337848/102914187-33c54100-4480-11eb-8db6-3ad4a0d27bfd.PNG)

**Comment by ckaran** [comment]
**MUCH** better!  

I agree that it's complex, maybe moving some of the stuff off of the slide and into notes on the same web page would help? That said, this level of complexity is really what is needed to fully explain futures.  They aren't magic, but the `async`, `await` syntax tends to make them appear so.  This level of explanation is what demystifies what is going on.  Once someone has fully read the slides and your explanations, they should be able to write their own [`join!()`](https://docs.rs/futures/0.3.8/futures/macro.join.html) or [`select!()`](https://docs.rs/futures/0.3.8/futures/macro.select.html), at least for two futures.  After reading your code, they should be able to write their own executors and reactors.  Once they're able to do all that, they'll be able to really use futures.

**Comment by cfsamson** [comment]
Thanks! That's great to hear 😃. This issue expanded a bit beyond what I first thought but I think (hope) the book is better for it. Even though the slides got a bit complex I don't think they're over the top yet. We do go pretty deep into explaining trait objects and generators on the following pages and a deeper dive into runtimes is also available in @stjepangs articles.

Thank you very much for good feedback and discussion on this topic. I've enjoyed it a lot!

Here is the end result: 
https://cfsamson.github.io/books-futures-explained/2_a_mental_model_for_futures.html

**Comment by ckaran** [comment]
It looks great!

My current plan is to leave this alone for a week or two, and then come back and re-read the book; my hope is that will help me really dig in and see everything more clearly, and make any further necessary suggestions.  However, I think we can close this issue now, you did a superb job!

**Comment by cfsamson** [comment]
Thanks. Absolutely, let me know if you come up with any ideas later on.
