### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by eagleshine** [cfsamson/books-futures-explained#33]
The links in the third paragraph in introduction under `What this book covers` is broken. The relevant texts:

```
The way you should go about it is to read this book first, then continue reading the articles from stejpang to learn more about runtimes and how they work, especially:

Build your own block_on()
Build your own executor
```

**Comment by cfsamson** [comment]
Thanks for letting me know. The whole blog is down so I added web.archive links to them.

**Comment by tl-christopher-fleetwood** [comment]
Seems even the archive links are broken now!
