### ISSUE TITLE
[typo] and and

### ISSUE THREAD

**Issue by alexxroche** [cfsamson/books-futures-explained#36]
https://github.com/cfsamson/books-futures-explained/blob/master/src/1_futures_in_rust.md
"and and"

(You should try reading your work aloud, as one of the editing stages.)

**Comment by cfsamson** [comment]
Yeah, I changed that paragraph yesterday based on some feedback and I obviously didn't read that through. That's embarrassing, sorry about that. I re-worded the whole paragraph now so it's a bit better.
