### ISSUE TITLE
pinning to the stack example is unclear

### ISSUE THREAD

**Issue by MarinPostma** [cfsamson/books-futures-explained#6]
Hello @cfsamson, 
first of all thank you for your amazing work on this book, it is a pleasure to read.

I have some observation about your example on pinning on the stack:

```rust 
pub fn main() {
    let mut test1 = Test::new("test1");
    let mut test1 = unsafe { Pin::new_unchecked(&mut test1) };
    Test::init(test1.as_mut());
     
    let mut test2 = Test::new("test2");
    let mut test2 = unsafe { Pin::new_unchecked(&mut test2) };
    Test::init(test2.as_mut());

    println!("a: {}, b: {}", Test::a(test1.as_ref()), Test::b(test1.as_ref()));
    std::mem::swap(test1.as_mut(), test2.as_mut());
    println!("a: {}, b: {}", Test::a(test2.as_ref()), Test::b(test2.as_ref()));
}
```

the compilation error you get there is:
```
expected `&mut _`, found struct `std::pin::Pin`
```
but this error is unrelated to the problem at hand.  `mem::swap` expects `&mut T`,  and you're feeding it a `Pin<&mut T>`, hence the complaint, that is easily fixed like so:
```rust
    std::mem::swap(&mut test1.as_mut(), &mut test2.as_mut());
```

and thus moving pointers to the `Pin` around.

I think what you meant to do was:

```rust 
std::mem::swap(test1.get_mut(), test2.get_mut());
```

get mut gives you a `&'a mut T`, and, when you try to move that, you get the compiling error:

```
error[E0277]: `std::marker::PhantomPinned` cannot be unpinned
  --> src/main.rs:47:43
   |
47 |     std::mem::swap(test1.get_mut(), test2.get_mut());
   |                                           ^^^^^^^ within `Test`, the trait `std::
marker::Unpin` is not implemented for `std::marker::PhantomPinned`
   |
   = note: required because it appears within the type `Test`
```

I'd be happy to make the correction, if you want. :)

**Comment by cfsamson** [comment]
Thanks for the feedback, glad to hear you enjoyed it. 

Yes, you're absolutely right! This is a much better error to display (and the one I thought I had). I'm working on some improvements on the book now so I can make this change right away.

**Comment by MarinPostma** [comment]
closing as this is now fixed
